AWSTemplateFormatVersion: 2010-09-09
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Global
        Parameters:
          - Client
    ParameterLabels:
      Client:
        default: Cliente
Parameters:
  Client:
    Type: String
    Description: O nome do cliente
    Default: sptech
Resources:
  BucketUtils:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: adoptai-utils-dev-c

  CustomLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Runtime: python3.9
      Timeout: 300
      Code:
        ZipFile: |
          import boto3
          import urllib.request
          import zipfile
          import os

          def handler(event, context):

              bucket_utils = os.environ['BUCKET_UTILS']

              s3 = boto3.client('s3')
              url = "https://raw.githubusercontent.com/Grupo-09-2024-SPTECH/infra-cloud/main/Lambda%20Codes/raw_trusted/main.py"  # URL do arquivo no GitHub
              file_path = "/tmp/main.py"
              zip_path = "/tmp/lambda_package_raw_trusted.zip"
              
              # Download do arquivo do GitHub
              urllib.request.urlretrieve(url, file_path)
              
              # Compactação do arquivo em um arquivo ZIP
              with zipfile.ZipFile(zip_path, 'w') as zipf:
                  # Adiciona o arquivo ao ZIP com o caminho dentro do ZIP especificado
                  zipf.write(file_path, 'raw_trusted/main.py')
              
              # Upload do arquivo ZIP para o S3
              s3.upload_file(zip_path, bucket_utils, 'lambda_zip/lambda_package_raw_trusted.zip')
              
              return {
                  'statusCode': 200,
                  'body': 'Upload and zip successful'
              }
      Environment:
        Variables:
          BUCKET_UTILS: adoptai-utils-dev-c

  CustomResource:
    Type: Custom::UploadFile
    Properties:
      ServiceToken: !GetAtt CustomLambdaFunction.Arn
      BUCKET_UTILS: adoptai-utils-dev-c