AWSTemplateFormatVersion: 2010-09-09
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Global
        Parameters:
          - Client
    ParameterLabels:
      Client:
        default: Cliente
Parameters:
  Client:
    Type: String
    Description: O nome do cliente
    Default: sptech
Resources:
  SqsRaw:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: adoptai-raw-prod-tcc-sqs
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 900
    DependsOn: CustomResource

  SnsRaw:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: adoptai-raw-prod-tcc-sns
      Subscription:
        - Endpoint: !GetAtt SqsRaw.Arn
          Protocol: sqs
    DependsOn: CustomResource

  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "sns:Publish"
              - "sns:GetTopicAttributes"
            Principal: "*"
            Resource: "*"
      Topics:
        - !Ref SnsRaw
    DependsOn: CustomResource

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SqsRaw
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: "*"
    DependsOn: CustomResource

  BucketRaw:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: adoptai-raw-prod-tcc
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref SnsRaw
            Event: s3:ObjectCreated:*
    DependsOn: CustomResource

  BucketTrusted:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: adoptai-trusted-prod-tcc
    DependsOn: CustomResource

  BucketUtils:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: adoptai-utils-prod-tcc

  CustomLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Runtime: python3.8
      Timeout: 300
      Code:
        ZipFile: |
          import boto3
          import urllib.request
          import zipfile
          import os
          import cfnresponse

          def handler(event, context):

              try:
                  bucket_utils = os.environ['BUCKET_UTILS']

                  s3 = boto3.client('s3')
                  url = "https://raw.githubusercontent.com/Grupo-09-2024-SPTECH/infra-cloud/main/Lambda%20Codes/raw_trusted/main.py"  # URL do arquivo no GitHub
                  file_path = "/tmp/main.py"
                  zip_path = "/tmp/lambda_package_raw_trusted.zip"
                  
                  # Download do arquivo do GitHub
                  urllib.request.urlretrieve(url, file_path)
                  
                  # Compactação do arquivo em um arquivo ZIP
                  with zipfile.ZipFile(zip_path, 'w') as zipf:
                      # Adiciona o arquivo ao ZIP com o caminho dentro do ZIP especificado
                      zipf.write(file_path, 'raw_trusted/main.py')
                  
                  # Upload do arquivo ZIP para o S3
                  s3.upload_file(zip_path, bucket_utils, 'lambda_zip/lambda_package_raw_trusted.zip')

                  # Enviar resposta de sucesso para o CloudFormation
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {'Message': 'Upload and zip successful'})

              except Exception as e:
                  # Em caso de falha, enviar resposta de falha para o CloudFormation
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Message': str(e)})

      Environment:
        Variables:
          BUCKET_UTILS: adoptai-utils-prod-tcc

  CustomResource:
    Type: Custom::UploadFile
    Properties:
      ServiceToken: !GetAtt CustomLambdaFunction.Arn
      BUCKET_UTILS: adoptai-utils-prod-tcc
    DependsOn: BucketUtils

  LambdaRawTrusted:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 900
      MemorySize: 5120
      Runtime: python3.8
      Handler: raw_trusted/main.lambda_handler
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      FunctionName: adoptai-raw-trusted-prod-tcc
      Layers:
        # - arn:aws:lambda:us-east-1:446751924810:layer:python-3-8-scikit-learn-0-23-1:2
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python38:7
      Environment:
        Variables:
          BUCKET_RAW: adoptai-raw-prod-tcc
          BUCKET_TRUSTED: adoptai-trusted-prod-tcc
      Code:
        S3Bucket: adoptai-utils-prod-tcc
        S3Key: lambda_zip/lambda_package_raw_trusted.zip
    DependsOn: CustomResource
  
  RawPermissionInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaRawTrusted
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt SqsRaw.Arn
    DependsOn: LambdaRawTrusted

  LambdaRawTrusteprodent:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: !GetAtt SqsRaw.Arn
      FunctionName: !Ref LambdaRawTrusted
    DependsOn: LambdaRawTrusted
